# version: '3.8'
# services:
#   frontend:
#     build: ./front-end
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_BASE=http://backend:3000
#       - VITE_COMPILER_API=http://compiler:8000
#     depends_on:
#       - backend
#       - compiler
#     command: sh -c "npm install && npm run dev -- --host"
#   backend:
#       build: ./back-end
#       ports:
#         - "3000:3000"
#       environment:
#         - PORT=3000
#         - COMPILER_SECRET=secret123
#       depends_on:
#         - mongo
#   compiler:
#       build: ./compiler
#       ports:
#         - "8000:8000"
#       environment:
#         - PORT=8000
#         - COMPILER_SECRET=secret123
#       depends_on:
#         - backend
#   mongo:
#       image: mongo:latest
#       ports:
#         - "27017:27017"
#       volumes:
#         - mongo-data:/data/db

#   volumes:
#     mongo-data:
version: '3.8'
services:
  compiler:
    build: ./compiler
    network_mode: "host"  # ✅ use host network
    environment:
      - PORT=5000
      # - MONGO_URI=your-uri
      - COMPILER_SECRET=blitzkrieg
      - JWT_SECRET=blitzkrieg
      - GEMINI_API_KEY=AIzaSyBSvCqYfJD12JKM7IdqL-ZAUDOjdzoBixM
      - PROMPT=You are an intelligent code assistant in an online coding judge. Given a problem statement and the user submitted code which may be incomplete or incorrect, generate a short, helpful hint that nudges the user toward the correct solution without revealing the full answer. Focus on identifying key mistakes, missing logic, or overlooked concepts. Your response should be Short and clear 1 to 2 sentences max, encouraging and constructive, and focused on conceptual guidance, not direct code.
      - BACKEND_URL=http://localhost:3000  # ✅ Now this will work!
